export const ROUTES = {
  login: "/login",
  reports: "/reports",
  applications: "/applications",
  applicationsPending: "/applications/pending",
  applicationDetail: (id: string) => `/applications/${id}`,
  profile: "/profile",
  settings: "/settings",
  signingWorkflows: "/settings/signing-workflows",
  signingWorkflowNew: "/settings/signing-workflows/new",
  signingWorkflowEdit: (id: string) => `/settings/signing-workflows/${id}`,
  signers: "/settings/signers",
  signerNew: "/settings/signers/new",
  signerEdit: (id: string) => `/settings/signers/${id}`,
  roles: "/settings/roles",
  roleNew: "/settings/roles/new",
  roleEdit: (id: string) => `/settings/roles/${id}`,
} as const;
